services:
  server:
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:${SERVER_PORT:-4000}"
    volumes:
      - ./server:/server-app
      #  - /server-app/node_modules
    env_file:
      - path: server/.env
        required: true
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}

  # db:
  #   image: postgres:16
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
